import { ModuleWithProviders, NgModule } from '@angular/core';
import {
  NbThemeModule,
  NbIconModule,
  NbButtonModule,
  NbA11yModule,
  NbAccordionModule,
  NbActionsModule,
  NbAlertModule,
  NbAutocompleteModule,
  NbBadgeModule,
  NbBaseCalendarModule,
  NbBidiModule,
  NbCalendarKitModule,
  NbCalendarModule,
  NbCalendarRangeModule,
  NbCardModule,
  NbCdkAdapterModule,
  NbCdkMappingModule,
  NbChatModule,
  NbCheckboxModule,
  NbContextMenuModule,
  NbDatepickerModule,
  NbDialogModule,
  NbFormFieldModule,
  NbInputModule,
  NbLayoutModule,
  NbListModule,
  NbMenuModule,
  NbOptionModule,
  NbOverlayModule,
  NbPopoverModule,
  NbProgressBarModule,
  NbRadioModule,
  NbRouteTabsetModule,
  NbSearchModule,
  NbSelectModule,
  NbSidebarModule,
  NbSpinnerModule,
  NbStepperModule,
  NbTableModule,
  NbTabsetModule,
  NbTimepickerModule,
  NbToastrModule,
  NbToggleModule,
  NbTooltipModule,
  NbTreeGridModule,
  NbUserModule,
  NbWindowModule,
} from '@nebular/theme';

import {
  NbEvaIconsModule
} from '@nebular/eva-icons';
export const NEBULAR_MODULES = [
  NbIconModule,
  NbButtonModule,
  NbA11yModule,
  NbAccordionModule,
  NbActionsModule,
  NbAlertModule,
  NbAutocompleteModule,
  NbBadgeModule,
  NbBaseCalendarModule,
  NbBidiModule,
  NbCalendarKitModule,
  NbCalendarModule,
  NbCalendarRangeModule,
  NbCardModule,
  NbCdkAdapterModule,
  NbCdkMappingModule,
  NbChatModule,
  NbCheckboxModule,
  NbContextMenuModule,
  NbDatepickerModule,
  NbDialogModule,
  NbFormFieldModule,
  NbInputModule,
  NbLayoutModule,
  NbListModule,
  NbMenuModule,
  NbOptionModule,
  NbOverlayModule,
  NbPopoverModule,
  NbProgressBarModule,
  NbRadioModule,
  NbRouteTabsetModule,
  NbSearchModule,
  NbSelectModule,
  NbSidebarModule,
  NbSpinnerModule,
  NbStepperModule,
  NbTableModule,
  NbTabsetModule,
  NbTimepickerModule,
  NbToastrModule,
  NbToggleModule,
  NbTooltipModule,
  NbTreeGridModule,
  NbUserModule,
  NbWindowModule,
  NbEvaIconsModule,
];

@NgModule({
  exports: [...NEBULAR_MODULES]
})
export class NebularModule {
  static forRoot(): ModuleWithProviders<NebularModule> {
    return {
      ngModule: NebularModule,
      providers: [
        ...NbThemeModule.forRoot({ name: 'default' }).providers,
        ...NbSidebarModule.forRoot().providers,
        ...NbMenuModule.forRoot().providers,
        ...NbDatepickerModule.forRoot().providers,
        ...NbDialogModule.forRoot().providers,
        ...NbWindowModule.forRoot().providers,
        ...NbToastrModule.forRoot().providers,
      ]
    };
  }
}
